/*
=======================================================================
 SOLUCIÓN DOCENTE
 Consultas Distribuidas en SQL Server
 Linked Server + CASE WHEN + SUM(CASE WHEN...) + AVG + MIN + MAX
 + ROW_NUMBER()
=======================================================================

ESCENARIO
---------
Instancia 1:
    BD_REGION_1
    BD_REGION_2

Instancia 2:
    BD_REGION_3

Linked Server creado desde Instancia 1:
    SERVIDOR_REGION3

Tabla regional:
    dbo.CONSUMO_REGIONAL

Columnas utilizadas:
    ABONADO, TRAMO, LNEGOCIO, SEGMENTO, DIA, ANTENA,
    ZONA, EVENTOS, MB, MINUTOS, INGRESO

IMPORTANTE:
- Ejecutar estas consultas desde la Instancia 1.
- Si el Linked Server tiene otro nombre, sustituir SERVIDOR_REGION3.
=======================================================================
*/


/*=====================================================================
 EJERCICIO 1. VERIFICAR LOS DATOS LOCALES
=====================================================================*/

SELECT
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT ABONADO) AS TOTAL_ABONADOS
FROM BD_REGION_1.dbo.CONSUMO_REGIONAL;

SELECT
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT ABONADO) AS TOTAL_ABONADOS
FROM BD_REGION_2.dbo.CONSUMO_REGIONAL;


/*=====================================================================
 EJERCICIO 2. PROBAR EL LINKED SERVER
=====================================================================*/

EXEC master.dbo.sp_testlinkedserver N'SERVIDOR_REGION3';

SELECT TOP (10) *
FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL];


/*=====================================================================
 EJERCICIO 3. COMPARAR CANTIDAD DE REGISTROS POR REGIÓN
=====================================================================*/

SELECT 'REGION 1' AS REGION, COUNT(*) AS TOTAL_REGISTROS
FROM BD_REGION_1.dbo.CONSUMO_REGIONAL

UNION ALL

SELECT 'REGION 2', COUNT(*)
FROM BD_REGION_2.dbo.CONSUMO_REGIONAL

UNION ALL

SELECT 'REGION 3', COUNT(*)
FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL];


/*=====================================================================
 PATRÓN BASE: CONSOLIDAR LAS TRES REGIONES
 ----------------------------------------------------------------------
 Este CTE se repetirá en los ejercicios para que cada solución pueda
 ejecutarse de manera independiente.
=====================================================================*/

WITH CONSUMO_NACIONAL AS
(
    SELECT ABONADO, TRAMO, LNEGOCIO, SEGMENTO, DIA, ANTENA,
           ZONA, EVENTOS, MB, MINUTOS, INGRESO
    FROM BD_REGION_1.dbo.CONSUMO_REGIONAL

    UNION ALL

    SELECT ABONADO, TRAMO, LNEGOCIO, SEGMENTO, DIA, ANTENA,
           ZONA, EVENTOS, MB, MINUTOS, INGRESO
    FROM BD_REGION_2.dbo.CONSUMO_REGIONAL

    UNION ALL

    SELECT ABONADO, TRAMO, LNEGOCIO, SEGMENTO, DIA, ANTENA,
           ZONA, EVENTOS, MB, MINUTOS, INGRESO
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
)
SELECT TOP (100) *
FROM CONSUMO_NACIONAL
ORDER BY DIA, ZONA, ABONADO;


/*=====================================================================
 EJERCICIO 4. INGRESO TOTAL POR ZONA
=====================================================================*/

WITH CONSUMO_NACIONAL AS
(
    SELECT ZONA, INGRESO FROM BD_REGION_1.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ZONA, INGRESO FROM BD_REGION_2.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ZONA, INGRESO
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
)
SELECT
    ZONA,
    SUM(INGRESO) AS TOTAL_INGRESO
FROM CONSUMO_NACIONAL
GROUP BY ZONA
ORDER BY TOTAL_INGRESO DESC;


/*=====================================================================
 EJERCICIO 5. CASE WHEN - CLASIFICACIÓN DEL CONSUMO DE MB
=====================================================================*/

WITH CONSUMO_NACIONAL AS
(
    SELECT ABONADO, DIA, ZONA, MB, INGRESO
    FROM BD_REGION_1.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ABONADO, DIA, ZONA, MB, INGRESO
    FROM BD_REGION_2.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ABONADO, DIA, ZONA, MB, INGRESO
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
)
SELECT
    ABONADO,
    DIA,
    ZONA,
    MB,
    INGRESO,
    CASE
        WHEN MB = 0 THEN 'SIN CONSUMO'
        WHEN MB <= 100 THEN 'CONSUMO BAJO'
        WHEN MB <= 500 THEN 'CONSUMO MEDIO'
        WHEN MB <= 1000 THEN 'CONSUMO ALTO'
        WHEN MB <=2500 THEN 'CONSUMO MUY ALTO' 
        ELSE 'CONSUMO EXTREMADAMENTE ALTO'
    END AS CLASIFICACION_CONSUMO
FROM CONSUMO_NACIONAL;

-- DUPLCIADO CLASES
WITH CONSUMO_NACIONAL AS
(
    SELECT ABONADO, DIA, ZONA, MB, INGRESO
    FROM BD_REGION_1.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ABONADO, DIA, ZONA, MB, INGRESO
    FROM BD_REGION_2.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ABONADO, DIA, ZONA, MB, INGRESO
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
)
SELECT
    ZONA,
    CASE
        WHEN MB = 0 THEN 'SIN CONSUMO'
        WHEN MB <= 100 THEN 'CONSUMO BAJO'
        WHEN MB <= 500 THEN 'CONSUMO MEDIO'
        WHEN MB <= 1000 THEN 'CONSUMO ALTO'
        WHEN MB <=2500 THEN 'CONSUMO MUY ALTO' 
        ELSE 'CONSUMO EXTREMADAMENTE ALTO'
    END AS CLASIFICACION_CONSUMO,
    sum(MB)/1024 as GB,
    sum(INGRESO) as monto
FROM CONSUMO_NACIONAL
group by ZONA,
    CASE
        WHEN MB = 0 THEN 'SIN CONSUMO'
        WHEN MB <= 100 THEN 'CONSUMO BAJO'
        WHEN MB <= 500 THEN 'CONSUMO MEDIO'
        WHEN MB <= 1000 THEN 'CONSUMO ALTO'
        WHEN MB <=2500 THEN 'CONSUMO MUY ALTO' 
        ELSE 'CONSUMO EXTREMADAMENTE ALTO'
    END
 having CASE
        WHEN MB = 0 THEN 'SIN CONSUMO'
        WHEN MB <= 100 THEN 'CONSUMO BAJO'
        WHEN MB <= 500 THEN 'CONSUMO MEDIO'
        WHEN MB <= 1000 THEN 'CONSUMO ALTO'
        WHEN MB <=2500 THEN 'CONSUMO MUY ALTO' 
        ELSE 'CONSUMO EXTREMADAMENTE ALTO'
    END = 'CONSUMO BAJO'
 order by gb asc

;


/*=====================================================================
 EJERCICIO 6. SUM(CASE WHEN...) - INGRESO POR ZONA EN COLUMNAS
=====================================================================*/

WITH CONSUMO_NACIONAL AS
(
    SELECT ZONA, INGRESO FROM BD_REGION_1.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ZONA, INGRESO FROM BD_REGION_2.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ZONA, INGRESO
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
)
SELECT
    SUM(CASE WHEN ZONA = 'CAPITAL'
             THEN INGRESO ELSE 0 END) AS CAPITAL,

    SUM(CASE WHEN ZONA = 'SUR ORIENTE'
             THEN INGRESO ELSE 0 END) AS SUR_ORIENTE,

    SUM(CASE WHEN ZONA = 'OCCIDENTE'
             THEN INGRESO ELSE 0 END) AS OCCIDENTE,

    SUM(CASE WHEN ZONA = 'ZONA NORTE'
             THEN INGRESO ELSE 0 END) AS ZONA_NORTE,

    SUM(CASE WHEN ZONA = 'ZONA CENTRO'
             THEN INGRESO ELSE 0 END) AS ZONA_CENTRO,

    SUM(CASE WHEN ZONA = 'REGIONES AUTONOMAS'
             THEN INGRESO ELSE 0 END) AS REGIONES_AUTONOMAS,

    SUM(INGRESO) AS TOTAL_NACIONAL
FROM CONSUMO_NACIONAL;

-- duplicado clases
WITH CONSUMO_NACIONAL AS
(
    SELECT ZONA, sum(INGRESO) monto, dia FROM BD_REGION_1.dbo.CONSUMO_REGIONAL
    group by zona, dia
    UNION ALL
    SELECT ZONA, sum(INGRESO) monto, dia FROM BD_REGION_2.dbo.CONSUMO_REGIONAL
    group by zona, dia
    UNION ALL
    SELECT ZONA, sum(INGRESO) monto, dia
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
    group by zona, dia
)
SELECT
    left(dia, 6) as mes,
    SUM(CASE WHEN ZONA = 'CAPITAL'
             THEN monto ELSE 0 END) AS CAPITAL,

    SUM(CASE WHEN ZONA = 'SUR ORIENTE'
             THEN monto ELSE 0 END) AS SUR_ORIENTE,

    SUM(CASE WHEN ZONA = 'OCCIDENTE'
             THEN monto ELSE 0 END) AS OCCIDENTE,

    SUM(CASE WHEN ZONA = 'ZONA NORTE'
             THEN monto ELSE 0 END) AS ZONA_NORTE,

    SUM(CASE WHEN ZONA = 'ZONA CENTRO'
             THEN monto ELSE 0 END) AS ZONA_CENTRO,

    SUM(CASE WHEN ZONA = 'REGIONES AUTONOMAS'
             THEN monto ELSE 0 END) AS REGIONES_AUTONOMAS,

    SUM(monto) AS TOTAL_NACIONAL
    

FROM CONSUMO_NACIONAL
group by left(dia, 6)
order by 1 ;


-- RETO CON MB 
WITH CONSUMO_NACIONAL AS
(
    SELECT ZONA, MB FROM BD_REGION_1.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ZONA, MB FROM BD_REGION_2.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ZONA, MB
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
)
SELECT
    SUM(CASE WHEN ZONA = 'CAPITAL'
             THEN MB ELSE 0 END) AS CAPITAL,

    SUM(CASE WHEN ZONA = 'SUR ORIENTE'
             THEN MB ELSE 0 END) AS SUR_ORIENTE,

    SUM(CASE WHEN ZONA = 'OCCIDENTE'
             THEN MB ELSE 0 END) AS OCCIDENTE,

    SUM(CASE WHEN ZONA = 'ZONA NORTE'
             THEN MB ELSE 0 END) AS ZONA_NORTE,

    SUM(CASE WHEN ZONA = 'ZONA CENTRO'
             THEN MB ELSE 0 END) AS ZONA_CENTRO,

    SUM(CASE WHEN ZONA = 'REGIONES AUTONOMAS'
             THEN MB ELSE 0 END) AS REGIONES_AUTONOMAS,

    SUM(MB) AS TOTAL_NACIONAL
FROM CONSUMO_NACIONAL;

/*=====================================================================
 EJERCICIO 7. SUM(CASE WHEN...) POR MES
=====================================================================*/

WITH CONSUMO_NACIONAL AS
(
    SELECT DIA, ZONA, INGRESO FROM BD_REGION_1.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT DIA, ZONA, INGRESO FROM BD_REGION_2.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT DIA, ZONA, INGRESO
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
)
SELECT
    DIA / 100 AS PERIODO,

    SUM(CASE WHEN ZONA = 'CAPITAL'
             THEN INGRESO ELSE 0 END) AS CAPITAL,

    SUM(CASE WHEN ZONA = 'SUR ORIENTE'
             THEN INGRESO ELSE 0 END) AS SUR_ORIENTE,

    SUM(CASE WHEN ZONA = 'OCCIDENTE'
             THEN INGRESO ELSE 0 END) AS OCCIDENTE,

    SUM(CASE WHEN ZONA = 'ZONA NORTE'
             THEN INGRESO ELSE 0 END) AS ZONA_NORTE,

    SUM(CASE WHEN ZONA = 'ZONA CENTRO'
             THEN INGRESO ELSE 0 END) AS ZONA_CENTRO,

    SUM(CASE WHEN ZONA = 'REGIONES AUTONOMAS'
             THEN INGRESO ELSE 0 END) AS REGIONES_AUTONOMAS

FROM CONSUMO_NACIONAL
GROUP BY DIA / 100
ORDER BY PERIODO;


/*=====================================================================
 EJERCICIO 8. AVG - PROMEDIOS POR ZONA
=====================================================================*/

WITH CONSUMO_NACIONAL AS
(
    SELECT ZONA, EVENTOS, MB, MINUTOS, INGRESO
    FROM BD_REGION_1.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ZONA, EVENTOS, MB, MINUTOS, INGRESO
    FROM BD_REGION_2.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ZONA, EVENTOS, MB, MINUTOS, INGRESO
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
)
SELECT
    ZONA,
    AVG(MB) AS PROMEDIO_MB,
    AVG(MINUTOS) AS PROMEDIO_MINUTOS,
    AVG(INGRESO) AS PROMEDIO_INGRESO,
    AVG(CAST(EVENTOS AS DECIMAL(18,2))) AS PROMEDIO_EVENTOS
FROM CONSUMO_NACIONAL
GROUP BY ZONA
ORDER BY ZONA;


/*=====================================================================
 EJERCICIO 9. MIN Y MAX POR ZONA
=====================================================================*/

WITH CONSUMO_NACIONAL AS
(
    SELECT ZONA, MB, MINUTOS, INGRESO
    FROM BD_REGION_1.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ZONA, MB, MINUTOS, INGRESO
    FROM BD_REGION_2.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ZONA, MB, MINUTOS, INGRESO
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
)
SELECT
    ZONA,
    MIN(MB) AS MIN_MB,
    MAX(MB) AS MAX_MB,
    MIN(MINUTOS) AS MIN_MINUTOS,
    MAX(MINUTOS) AS MAX_MINUTOS,
    MIN(INGRESO) AS MIN_INGRESO,
    MAX(INGRESO) AS MAX_INGRESO
FROM CONSUMO_NACIONAL
GROUP BY ZONA
ORDER BY ZONA;

--duplicado clases
WITH CONSUMO_NACIONAL AS
(
    SELECT ZONA, MB, MINUTOS, INGRESO, dia
    FROM BD_REGION_1.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ZONA, MB, MINUTOS, INGRESO, dia
    FROM BD_REGION_2.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ZONA, MB, MINUTOS, INGRESO, dia
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
)
SELECT
    dia,
    ZONA,
    MIN(MB) AS MIN_MB,
    MAX(MB) AS MAX_MB,
    MIN(MINUTOS) AS MIN_MINUTOS,
    MAX(MINUTOS) AS MAX_MINUTOS,
    MIN(INGRESO) AS MIN_INGRESO,
    MAX(INGRESO) AS MAX_INGRESO
FROM CONSUMO_NACIONAL
GROUP BY ZONA, dia
ORDER BY zona;



/*=====================================================================
 EJERCICIO 10. SUM + AVG + MIN + MAX POR MES
=====================================================================*/

WITH CONSUMO_NACIONAL AS
(
    SELECT DIA, MB, INGRESO FROM BD_REGION_1.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT DIA, MB, INGRESO FROM BD_REGION_2.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT DIA, MB, INGRESO
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
)
SELECT
    DIA / 100 AS PERIODO,
    SUM(MB) AS TOTAL_MB,
    AVG(MB) AS PROMEDIO_MB,
    MIN(MB) AS MIN_MB,
    MAX(MB) AS MAX_MB,
    SUM(INGRESO) AS TOTAL_INGRESO
FROM CONSUMO_NACIONAL
GROUP BY DIA / 100
ORDER BY PERIODO;


/*=====================================================================
 EJERCICIO 11. CASE WHEN + GROUP BY
=====================================================================*/

WITH CONSUMO_NACIONAL AS
(
    SELECT MB, INGRESO FROM BD_REGION_1.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT MB, INGRESO FROM BD_REGION_2.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT MB, INGRESO
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
),
CLASIFICADO AS
(
    SELECT
        MB,
        INGRESO,
        CASE
            WHEN MB = 0 THEN 'SIN CONSUMO'
            WHEN MB <= 100 THEN 'CONSUMO BAJO'
            WHEN MB <= 500 THEN 'CONSUMO MEDIO'
            ELSE 'CONSUMO ALTO'
        END AS CLASIFICACION
    FROM CONSUMO_NACIONAL
)
SELECT
    CLASIFICACION,
    COUNT(*) AS TOTAL_REGISTROS,
    SUM(MB) AS TOTAL_MB,
    AVG(INGRESO) AS PROMEDIO_INGRESO,
    MIN(INGRESO) AS MIN_INGRESO,
    MAX(INGRESO) AS MAX_INGRESO
FROM CLASIFICADO
GROUP BY CLASIFICACION
ORDER BY CLASIFICACION;


/*=====================================================================
 EJERCICIO 12. TOP 10 ANTENAS POR TRÁFICO NACIONAL
=====================================================================*/

WITH CONSUMO_NACIONAL AS
(
    SELECT ANTENA, ZONA, MB, MINUTOS, INGRESO
    FROM BD_REGION_1.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ANTENA, ZONA, MB, MINUTOS, INGRESO
    FROM BD_REGION_2.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ANTENA, ZONA, MB, MINUTOS, INGRESO
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
)
SELECT TOP (10)
    ANTENA,
    ZONA,
    SUM(MB) AS TOTAL_MB,
    AVG(MB) AS PROMEDIO_MB,
    MIN(MB) AS MIN_MB,
    MAX(MB) AS MAX_MB,
    SUM(MINUTOS) AS TOTAL_MINUTOS,
    SUM(INGRESO) AS TOTAL_INGRESO
FROM CONSUMO_NACIONAL
GROUP BY ANTENA, ZONA
ORDER BY TOTAL_MB DESC;


/*=====================================================================
 EJERCICIO 13. OPENQUERY - ESTADÍSTICAS DE REGION 3
=====================================================================*/

SELECT *
FROM OPENQUERY(
    SERVIDOR_REGION3,
    'SELECT
         ZONA,
         SUM(INGRESO) AS TOTAL_INGRESO,
         AVG(INGRESO) AS PROMEDIO_INGRESO,
         MIN(INGRESO) AS MIN_INGRESO,
         MAX(INGRESO) AS MAX_INGRESO
     FROM BD_REGION_3.dbo.CONSUMO_REGIONAL
     GROUP BY ZONA'
);

/* RETO FINAL */ 
-- 1 
WITH CONSUMO_NACIONAL AS
(
    SELECT DIA, ZONA, INGRESO
    FROM BD_REGION_1.dbo.CONSUMO_REGIONAL

    UNION ALL

    SELECT DIA, ZONA, INGRESO
    FROM BD_REGION_2.dbo.CONSUMO_REGIONAL

    UNION ALL

    SELECT DIA, ZONA, INGRESO
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
),
RESUMEN AS
(
    SELECT
        DIA / 100 AS PERIODO,
        ZONA,
        SUM(INGRESO) AS INGRESO_ZONA
    FROM CONSUMO_NACIONAL
    GROUP BY DIA / 100, ZONA
),
TOTALES AS
(
    SELECT
        PERIODO,
        SUM(INGRESO_ZONA) AS INGRESO_NACIONAL
    FROM RESUMEN
    GROUP BY PERIODO
)
SELECT
    R.PERIODO,
    R.ZONA,
    R.INGRESO_ZONA,
    CASE
        WHEN R.INGRESO_ZONA * 100.0 / T.INGRESO_NACIONAL >= 25
            THEN 'PARTICIPACION ALTA'
        WHEN R.INGRESO_ZONA * 100.0 / T.INGRESO_NACIONAL >= 15
            THEN 'PARTICIPACION MEDIA'
        ELSE 'PARTICIPACION BAJA'
    END AS CLASIFICACION
FROM RESUMEN R
INNER JOIN TOTALES T
    ON R.PERIODO = T.PERIODO
ORDER BY R.PERIODO, R.ZONA;

--2 
WITH CONSUMO_NACIONAL AS
(
    SELECT DIA, ZONA, INGRESO
    FROM BD_REGION_1.dbo.CONSUMO_REGIONAL

    UNION ALL

    SELECT DIA, ZONA, INGRESO
    FROM BD_REGION_2.dbo.CONSUMO_REGIONAL

    UNION ALL

    SELECT DIA, ZONA, INGRESO
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
)
SELECT
    DIA / 100 AS PERIODO,

    SUM(CASE WHEN ZONA = 'CAPITAL'
        THEN INGRESO ELSE 0 END) AS CAPITAL,

    SUM(CASE WHEN ZONA = 'SUR ORIENTE'
        THEN INGRESO ELSE 0 END) AS SUR_ORIENTE,

    SUM(CASE WHEN ZONA = 'OCCIDENTE'
        THEN INGRESO ELSE 0 END) AS OCCIDENTE,

    SUM(CASE WHEN ZONA = 'ZONA NORTE'
        THEN INGRESO ELSE 0 END) AS ZONA_NORTE,

    SUM(CASE WHEN ZONA = 'ZONA CENTRO'
        THEN INGRESO ELSE 0 END) AS ZONA_CENTRO,

    SUM(CASE WHEN ZONA = 'REGIONES AUTONOMAS'
        THEN INGRESO ELSE 0 END) AS REGIONES_AUTONOMAS

FROM CONSUMO_NACIONAL
GROUP BY DIA / 100
ORDER BY PERIODO;

/*=====================================================================
 EJERCICIO 14. ROW_NUMBER()
 RANKING MENSUAL: TOP 5 ANTENAS POR ZONA SEGÚN MB
=====================================================================*/

WITH CONSUMO_NACIONAL AS
(
    SELECT DIA, ZONA, ANTENA, MB
    FROM BD_REGION_1.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT DIA, ZONA, ANTENA, MB
    FROM BD_REGION_2.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT DIA, ZONA, ANTENA, MB
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
),
RESUMEN AS
(
    SELECT
        DIA / 100 AS PERIODO,
        ZONA,
        ANTENA,
        SUM(MB) AS TOTAL_MB
    FROM CONSUMO_NACIONAL
    GROUP BY DIA / 100, ZONA, ANTENA
),
RANKING AS
(
    SELECT
        PERIODO,
        ZONA,
        ANTENA,
        TOTAL_MB,
        ROW_NUMBER() OVER
        (
            PARTITION BY PERIODO, ZONA
            ORDER BY TOTAL_MB DESC, ANTENA
        ) AS POSICION
    FROM RESUMEN
)
SELECT
    PERIODO,
    ZONA,
    POSICION,
    ANTENA,
    TOTAL_MB
FROM RANKING
WHERE POSICION <= 5
ORDER BY PERIODO, ZONA, POSICION;


/*=====================================================================
 EJERCICIO 15. ROW_NUMBER()
 TOP 10 ANTENAS POR ZONA SEGÚN INGRESO
=====================================================================*/

WITH CONSUMO_NACIONAL AS
(
    SELECT ZONA, ANTENA, MB, MINUTOS, INGRESO
    FROM BD_REGION_1.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ZONA, ANTENA, MB, MINUTOS, INGRESO
    FROM BD_REGION_2.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ZONA, ANTENA, MB, MINUTOS, INGRESO
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
),
RESUMEN AS
(
    SELECT
        ZONA,
        ANTENA,
        SUM(INGRESO) AS TOTAL_INGRESO,
        SUM(MB) AS TOTAL_MB,
        SUM(MINUTOS) AS TOTAL_MINUTOS
    FROM CONSUMO_NACIONAL
    GROUP BY ZONA, ANTENA
),
RANKING AS
(
    SELECT
        ZONA,
        ANTENA,
        TOTAL_INGRESO,
        TOTAL_MB,
        TOTAL_MINUTOS,
        ROW_NUMBER() OVER
        (
            PARTITION BY ZONA
            ORDER BY TOTAL_INGRESO DESC, ANTENA
        ) AS POSICION
    FROM RESUMEN
)
SELECT
    ZONA,
    POSICION,
    ANTENA,
    TOTAL_INGRESO,
    TOTAL_MB,
    TOTAL_MINUTOS
FROM RANKING
WHERE POSICION <= 10
ORDER BY ZONA, POSICION;


/*=====================================================================
 EJERCICIO 16. ROW_NUMBER()
 RANKING MENSUAL DE ZONAS SEGÚN INGRESO
=====================================================================*/

WITH CONSUMO_NACIONAL AS
(
    SELECT DIA, ZONA, MB, MINUTOS, INGRESO
    FROM BD_REGION_1.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT DIA, ZONA, MB, MINUTOS, INGRESO
    FROM BD_REGION_2.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT DIA, ZONA, MB, MINUTOS, INGRESO
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
),
RESUMEN AS
(
    SELECT
        DIA / 100 AS PERIODO,
        ZONA,
        SUM(INGRESO) AS TOTAL_INGRESO,
        SUM(MB) AS TOTAL_MB,
        SUM(MINUTOS) AS TOTAL_MINUTOS
    FROM CONSUMO_NACIONAL
    GROUP BY DIA / 100, ZONA
),
RANKING AS
(
    SELECT
        PERIODO,
        ZONA,
        TOTAL_INGRESO,
        TOTAL_MB,
        TOTAL_MINUTOS,
        ROW_NUMBER() OVER
        (
            PARTITION BY PERIODO
            ORDER BY TOTAL_INGRESO DESC, ZONA
        ) AS POSICION
    FROM RESUMEN
)
SELECT
    PERIODO,
    POSICION,
    ZONA,
    TOTAL_INGRESO,
    TOTAL_MB,
    TOTAL_MINUTOS
FROM RANKING
ORDER BY PERIODO, POSICION;


/*=====================================================================
 EJERCICIO 17. ROW_NUMBER()
 TOP 5 ANTENAS POR LÍNEA DE NEGOCIO SEGÚN MB
=====================================================================*/

WITH CONSUMO_NACIONAL AS
(
    SELECT LNEGOCIO, ANTENA, MB, INGRESO
    FROM BD_REGION_1.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT LNEGOCIO, ANTENA, MB, INGRESO
    FROM BD_REGION_2.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT LNEGOCIO, ANTENA, MB, INGRESO
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
),
RESUMEN AS
(
    SELECT
        LNEGOCIO,
        ANTENA,
        SUM(MB) AS TOTAL_MB,
        AVG(MB) AS PROMEDIO_MB,
        SUM(INGRESO) AS TOTAL_INGRESO
    FROM CONSUMO_NACIONAL
    GROUP BY LNEGOCIO, ANTENA
),
RANKING AS
(
    SELECT
        LNEGOCIO,
        ANTENA,
        TOTAL_MB,
        PROMEDIO_MB,
        TOTAL_INGRESO,
        ROW_NUMBER() OVER
        (
            PARTITION BY LNEGOCIO
            ORDER BY TOTAL_MB DESC, ANTENA
        ) AS POSICION
    FROM RESUMEN
)
SELECT
    LNEGOCIO,
    POSICION,
    ANTENA,
    TOTAL_MB,
    PROMEDIO_MB,
    TOTAL_INGRESO
FROM RANKING
WHERE POSICION <= 5
ORDER BY LNEGOCIO, POSICION;


/*=====================================================================
 EJERCICIO 18. ROW_NUMBER() + CASE WHEN
 CLASIFICAR ANTENAS SEGÚN SU POSICIÓN NACIONAL
=====================================================================*/

WITH CONSUMO_NACIONAL AS
(
    SELECT ANTENA, MB
    FROM BD_REGION_1.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ANTENA, MB
    FROM BD_REGION_2.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ANTENA, MB
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
),
RESUMEN AS
(
    SELECT
        ANTENA,
        SUM(MB) AS TOTAL_MB
    FROM CONSUMO_NACIONAL
    GROUP BY ANTENA
),
RANKING AS
(
    SELECT
        ANTENA,
        TOTAL_MB,
        ROW_NUMBER() OVER
        (
            ORDER BY TOTAL_MB DESC, ANTENA
        ) AS POSICION
    FROM RESUMEN
),
CLASIFICADO AS
(
    SELECT
        ANTENA,
        TOTAL_MB,
        POSICION,
        CASE
            WHEN POSICION <= 10 THEN 'TRAFICO MUY ALTO'
            WHEN POSICION <= 50 THEN 'TRAFICO ALTO'
            WHEN POSICION <= 100 THEN 'TRAFICO MEDIO'
            ELSE 'TRAFICO REGULAR'
        END AS CLASIFICACION
    FROM RANKING
)
SELECT *
FROM CLASIFICADO
ORDER BY POSICION;


/*=====================================================================
 EJERCICIO 19. SUM(CASE WHEN...) SOBRE LA CLASIFICACIÓN DEL RANKING
=====================================================================*/

WITH CONSUMO_NACIONAL AS
(
    SELECT ANTENA, MB
    FROM BD_REGION_1.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ANTENA, MB
    FROM BD_REGION_2.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT ANTENA, MB
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
),
RESUMEN AS
(
    SELECT ANTENA, SUM(MB) AS TOTAL_MB
    FROM CONSUMO_NACIONAL
    GROUP BY ANTENA
),
RANKING AS
(
    SELECT
        ANTENA,
        TOTAL_MB,
        ROW_NUMBER() OVER
        (
            ORDER BY TOTAL_MB DESC, ANTENA
        ) AS POSICION
    FROM RESUMEN
)
SELECT
    SUM(CASE WHEN POSICION <= 10
             THEN 1 ELSE 0 END) AS TRAFICO_MUY_ALTO,

    SUM(CASE WHEN POSICION BETWEEN 11 AND 50
             THEN 1 ELSE 0 END) AS TRAFICO_ALTO,

    SUM(CASE WHEN POSICION BETWEEN 51 AND 100
             THEN 1 ELSE 0 END) AS TRAFICO_MEDIO,

    SUM(CASE WHEN POSICION > 100
             THEN 1 ELSE 0 END) AS TRAFICO_REGULAR
FROM RANKING;

/* REPORTE CONSOLIDADO */ 
WITH CONSUMO_NACIONAL AS
(
    SELECT 
        ABONADO,
        DIA,
        ZONA,
        EVENTOS,
        MB,
        MINUTOS,
        INGRESO
    FROM BD_REGION_1.dbo.CONSUMO_REGIONAL

    UNION ALL

    SELECT 
        ABONADO,
        DIA,
        ZONA,
        EVENTOS,
        MB,
        MINUTOS,
        INGRESO
    FROM BD_REGION_2.dbo.CONSUMO_REGIONAL

    UNION ALL

    SELECT 
        ABONADO,
        DIA,
        ZONA,
        EVENTOS,
        MB,
        MINUTOS,
        INGRESO
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
)

SELECT
    DIA / 100 AS PERIODO,
    ZONA,

    COUNT(DISTINCT ABONADO) AS CANTIDAD_ABONADOS,

    SUM(EVENTOS) AS TOTAL_EVENTOS,

    SUM(MB) AS TOTAL_MB,
    AVG(MB) AS PROMEDIO_MB,
    MIN(MB) AS MIN_MB,
    MAX(MB) AS MAX_MB,

    SUM(MINUTOS) AS TOTAL_MINUTOS,

    SUM(INGRESO) AS TOTAL_INGRESO,
    AVG(INGRESO) AS PROMEDIO_INGRESO,
    MIN(INGRESO) AS MIN_INGRESO,
    MAX(INGRESO) AS MAX_INGRESO

FROM CONSUMO_NACIONAL

GROUP BY 
    DIA / 100,
    ZONA

ORDER BY 
    PERIODO,
    ZONA;


/*=====================================================================
 EJERCICIO 20. RETO INTEGRADOR
 SUM + AVG + MIN + MAX + CASE WHEN + SUM(CASE WHEN...) + ROW_NUMBER()
=====================================================================*/

WITH CONSUMO_NACIONAL AS
(
    SELECT DIA, ZONA, MB, MINUTOS, INGRESO
    FROM BD_REGION_1.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT DIA, ZONA, MB, MINUTOS, INGRESO
    FROM BD_REGION_2.dbo.CONSUMO_REGIONAL
    UNION ALL
    SELECT DIA, ZONA, MB, MINUTOS, INGRESO
    FROM [SERVIDOR_REGION3].[BD_REGION_3].[dbo].[CONSUMO_REGIONAL]
),
RESUMEN AS
(
    SELECT
        DIA / 100 AS PERIODO,
        ZONA,

        SUM(MB) AS TOTAL_MB,
        AVG(MB) AS PROMEDIO_MB,
        MIN(MB) AS MIN_MB,
        MAX(MB) AS MAX_MB,

        SUM(MINUTOS) AS TOTAL_MINUTOS,

        SUM(INGRESO) AS TOTAL_INGRESO,
        AVG(INGRESO) AS PROMEDIO_INGRESO,
        MIN(INGRESO) AS MIN_INGRESO,
        MAX(INGRESO) AS MAX_INGRESO,

        SUM(CASE WHEN MB = 0 THEN 1 ELSE 0 END) AS SIN_CONSUMO,
        SUM(CASE WHEN MB > 0 AND MB <= 100 THEN 1 ELSE 0 END)
            AS CONSUMO_BAJO,
        SUM(CASE WHEN MB > 100 AND MB <= 500 THEN 1 ELSE 0 END)
            AS CONSUMO_MEDIO,
        SUM(CASE WHEN MB > 500 THEN 1 ELSE 0 END)
            AS CONSUMO_ALTO

    FROM CONSUMO_NACIONAL
    GROUP BY DIA / 100, ZONA
),
RANKING AS
(
    SELECT
        *,
        ROW_NUMBER() OVER
        (
            PARTITION BY PERIODO
            ORDER BY TOTAL_MB DESC, ZONA
        ) AS POSICION_MB
    FROM RESUMEN
)
SELECT
    PERIODO,
    POSICION_MB,
    ZONA,
    TOTAL_MB,
    PROMEDIO_MB,
    MIN_MB,
    MAX_MB,
    TOTAL_MINUTOS,
    TOTAL_INGRESO,
    PROMEDIO_INGRESO,
    MIN_INGRESO,
    MAX_INGRESO,
    SIN_CONSUMO,
    CONSUMO_BAJO,
    CONSUMO_MEDIO,
    CONSUMO_ALTO,

    CASE
        WHEN POSICION_MB = 1 THEN 'ZONA LIDER EN TRAFICO'
        WHEN POSICION_MB <= 3 THEN 'TRAFICO ALTO'
        ELSE 'TRAFICO RESTANTE'
    END AS CLASIFICACION_ZONA

FROM RANKING
ORDER BY PERIODO, POSICION_MB;


/*=====================================================================
 FIN DE LA SOLUCIÓN DOCENTE
=====================================================================*/
